//
// Created by Nikita Kruk on 16.07.18.
//

#ifndef SPC2FVMNONLINNONLOCEQSMOVIE_DEFINITIONS_HPP
#define SPC2FVMNONLINNONLOCEQSMOVIE_DEFINITIONS_HPP

typedef double Real;

#endif //SPC2FVMNONLINNONLOCEQSMOVIE_DEFINITIONS_HPP
